---
title: "lps1.1"
output: pdf_document
date: "2026-03-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-pkgs, message=FALSE}
library(Matrix)
library(readr)
library(data.table)
library(fastTopics)
#library(NNLM)
library(ebnm)
library(flashier)
#library(pathways)
#library(singlecelljamboreeR)
library(ggplot2)
library(ggrepel)
library(cowplot)
library(rsvd)
library(uwot)
```

## Prepare the data for analysis with fastTopics

Load the RNA-seq counts:

```{r load-counts}
read_lps_data <- function (file) {
  counts <- fread(file)
  class(counts) <- "data.frame"
  genes <- counts[,1]
  counts <- t(as.matrix(counts[,-1]))
  colnames(counts) <- genes
  samples <- rownames(counts)
  samples <- strsplit(samples,"_")
  samples <- data.frame(tissue    = sapply(samples,"[[",1),
                        timepoint = sapply(samples,"[[",2),
                        mouse     = sapply(samples,"[[",3))
  samples <- transform(samples,
                       tissue    = factor(tissue),
					   timepoint = factor(timepoint),
					   mouse     = factor(mouse))
  return(list(samples = samples,counts = counts))
}
out <- read_lps_data("../data/lps.csv.gz")
samples <- out$samples
counts  <- out$counts
rm(out)

```

Remove a sample that appears to be an outlier based on the NMF analyses:

```{r filter-outliers}
i       <- which(rownames(counts) != "iLN_d2_20")
samples <- samples[i,]
counts  <- counts[i,]
```

Remove genes that are expressed in fewer than 5 samples:

```{r filter-genes}
j <- which(colSums(counts > 0) > 4)
counts <- counts[,j]
```

This is the dimension of the data set we will analyze:

```{r dim-counts}
dim(counts)
```

## PCA

```{r}
# Use shifted log counts (cells x genes)
X <- counts

# Remove constant / zero-variance genes
keep <- apply(X, 2, sd) > 0
X_pca <- X[, keep]

# Perform PCA
pca <- prcomp(X_pca, scale. = TRUE)

df <- data.frame(
  PC1    = pca$x[, 1],
  PC2    = pca$x[, 2],
  tissue = samples$tissue,
  time   = samples$timepoint
)

ggplot(df, aes(PC1, PC2, color = tissue, shape = time)) +
  geom_point(size = 2) +
  scale_shape_manual(values = c(16, 17, 15, 3, 7, 8, 9)) +  # 7 distinct shapes
  theme_bw()+
  labs(title = "PCA of counts")

```

## Fit a topic model with K = 14 topics to the counts:

```{r fit-topic-model, cache=TRUE}
set.seed(1)
tm <- fit_poisson_nmf(counts,k = 14,init.method = "random",method = "em",
                      numiter = 20,verbose = "none",
					  control = list(numiter = 4,nc = 8,extrapolate = FALSE))
tm <- fit_poisson_nmf(counts,fit0 = tm,method = "scd",numiter = 40,
                      control = list(numiter = 4,nc = 8,extrapolate = TRUE),
					  verbose = "none")
tm_mn <- poisson2multinom(tm)
L <- tm_mn$L 
```

```{r}
rows <- order(samples$timepoint)
topic_colors <- c("magenta","darkorange","darkblue","forestgreen",
                  "dodgerblue","gray","red","olivedrab","darkmagenta",
                  "sienna","limegreen","royalblue","lightskyblue",
				  "gold")
samples <- transform(samples,
  tissue = factor(tissue,c("PBMC","BM","CO","SI","iLN","SP",
                           "TH","SK","BR","LI","HE","KI","LU")))
```
Structure plot comparing the topics to the tissue types:

```{r structure-plot-topic-model, fig.height=1.5, fig.width=7}
structure_plot(tm,grouping = samples$tissue,gap = 4,
               topics = 1:14,colors = topic_colors,
   		       loadings_order = rows) +
  labs(fill = "") +
  theme(axis.text.x = element_text(angle = 0,hjust = 0.5),
        legend.key.height = unit(0.01,"cm"),
        legend.key.width = unit(0.2,"cm"),
        legend.text = element_text(size = 6))
```
